flag_homepage:
    path:     /
    defaults: { _controller: FlagBundle:Default:index }

selectMode:
    path:     /selectMode
    defaults: { _controller: FlagBundle:Default:selectMode }

selectSet:
  path:     /selectSet/{mode}
  defaults: { _controller: FlagBundle:Default:selectSet }

#rotte di gioco nametoflag

play_ntf:
  path:     selectSet/play/ntf/{set}
  defaults: { _controller: FlagBundle:Game:nameToFlag }

play_fnt:
  path:     selectSet/play/ftn/{set}
  defaults: { _controller: FlagBundle:Game:flagToName }

records:
  path:     records
  defaults: { _controller: FlagBundle:Default:recordChoice }

recordsPage:
  path:     records/set/{set}
  defaults: { _controller: FlagBundle:Default:recordsPage }
