<?php

namespace FlagBundle\Repository;


/**
 * CountryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CountryRepository extends \Doctrine\ORM\EntityRepository
{
  public function findAllRecognizedCountries(){
    return $this->getEntityManager()->createQuery('SELECT c FROM FlagBundle:Country c WHERE c.isRecognized=1')
    ->getResult();
  }
}
