<?php

namespace FlagBundle\Repository;

/**
 * RecordRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RecordRepository extends \Doctrine\ORM\EntityRepository
{
  public function FindFtNByChosenSet($set){
    return $this->getEntityManager()->createQuery("SELECT r FROM FlagBundle:Record r WHERE r.flagset='$set' AND r.mode='ftn' ORDER BY r.points DESC")
    ->setMaxResults(10)->getResult();
  }


  public function FindNtFByChosenSet($set){
    return $this->getEntityManager()->createQuery("SELECT r FROM FlagBundle:Record r WHERE r.flagset='$set' AND r.mode='ntf' ORDER BY r.points DESC")
    ->setMaxResults(10)->getResult();
}
}
